version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"  # Vite dev server
      - "3000:3000"  # Backend API
    volumes:
      - .:/app
      - /app/node_modules
      - contract_uploads:/app/server/uploads
      - sqlite_data:/app/server/database
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://107.173.168.46:3000
      - HOST=0.0.0.0
    command: npm run dev:all

volumes:
  contract_uploads:
  sqlite_data: